openapi: 3.0.0
info:
  title: star-simulation
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  /simulation/create:
    parameters:
      - schema:
          type: string
        name: file
        required: true
    post:
      summary: create
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  turnLimit:
                    type: int
                  completedTurns:
                    type: int
                  currentTurnPos:
                    type: int
                  n_drones: 
                    type: int
                  n_suns:
                    type: int
                  n_stars:
                    type: int
                  potentialCellsToExplore:
                    type: int
                  exporedCells:
                    type: int
                  unExporedCells:
                    type: int
                  regionSize:
                    type: int
                  regionX:
                    type: int
                  regionY:
                    type: int
                  drones:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        x:
                          type: integer
                        'y':
                          type: integer
                        direction:
                          type: string
                  suns:
                    type: array
                    items:
                      type: object
                      properties:
                        x:
                          type: integer
                        'y':
                          type: integer
                  stars:
                    type: array
                    items:
                      type: object
                      properties:
                        x:
                          type: integer
                        'y':
                          type: integer
          application/xml:
            schema:
              type: object
              properties: {}

  /simulation/save:
    parameters:
      schema:
        type: string
        name: path
    get:
      summary: Saves simulation
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  turnLimit:
                    type: int
                  completedTurns:
                    type: int
                  currentTurnPos:
                    type: int
                  n_drones: 
                    type: int
                  n_suns:
                    type: int
                  n_stars:
                    type: int
                  potentialCellsToExplore:
                    type: int
                  exporedCells:
                    type: int
                  unExporedCells:
                    type: int
                  regionSize:
                    type: int
                  regionX:
                    type: int
                  regionY:
                    type: int
                  drones:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        x:
                          type: integer
                        'y':
                          type: integer
                        direction:
                          type: string
                  suns:
                    type: array
                    items:
                      type: object
                      properties:
                        x:
                          type: integer
                        'y':
                          type: integer
                  stars:
                    type: array
                    items:
                      type: object
                      properties:
                        x:
                          type: integer
                        'y':
                          type: integer
              examples:
                example-1: {}
      operationId: save
      description: Saves the current simulation to a file

  /simulation/rewind:
    parameters:
      - schema:
          type: number
        name: n_steps
        required: true
    get:
      summary: Rewinds simulation
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  turnLimit:
                    type: int
                  completedTurns:
                    type: int
                  currentTurnPos:
                    type: int
                  n_drones: 
                    type: int
                  n_suns:
                    type: int
                  n_stars:
                    type: int
                  potentialCellsToExplore:
                    type: int
                  exporedCells:
                    type: int
                  unExporedCells:
                    type: int
                  regionSize:
                    type: int
                  regionX:
                    type: int
                  regionY:
                    type: int
                  drones:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        x:
                          type: integer
                        'y':
                          type: integer
                        direction:
                          type: string
                  suns:
                    type: array
                    items:
                      type: object
                      properties:
                        x:
                          type: integer
                        'y':
                          type: integer
                  stars:
                    type: array
                    items:
                      type: object
                      properties:
                        x:
                          type: integer
                        'y':
                          type: integer
                example-1: {}
      operationId: rewind
      description: Rewind current state of the simulation by a certain number of steps

  /simulation/forward:
    parameters:
      - schema:
          type: number
        name: n_steps
        required: true
    get:
      summary: Forwards simulation
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  turnLimit:
                    type: int
                  completedTurns:
                    type: int
                  currentTurnPos:
                    type: int
                  n_drones: 
                    type: int
                  n_suns:
                    type: int
                  n_stars:
                    type: int
                  potentialCellsToExplore:
                    type: int
                  exporedCells:
                    type: int
                  unExporedCells:
                    type: int
                  regionSize:
                    type: int
                  regionX:
                    type: int
                  regionY:
                    type: int
                  drones:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        x:
                          type: integer
                        'y':
                          type: integer
                        direction:
                          type: string
                  suns:
                    type: array
                    items:
                      type: object
                      properties:
                        x:
                          type: integer
                        'y':
                          type: integer
                  stars:
                    type: array
                    items:
                      type: object
                      properties:
                        x:
                          type: integer
                        'y':
                          type: integer
              examples:
                example-1: {}
      operationId: forward
      description: Forwards the current state of the simulation by a certain number of steps
      
  /simulation/replay:
    parameters: []
    get:
      summary: Replays simulation
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  turnLimit:
                    type: int
                  completedTurns:
                    type: int
                  currentTurnPos:
                    type: int
                  n_drones: 
                    type: int
                  n_suns:
                    type: int
                  n_stars:
                    type: int
                  potentialCellsToExplore:
                    type: int
                  exporedCells:
                    type: int
                  unExporedCells:
                    type: int
                  regionSize:
                    type: int
                  regionX:
                    type: int
                  regionY:
                    type: int
                  drones:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        x:
                          type: integer
                        'y':
                          type: integer
                        direction:
                          type: string
                  suns:
                    type: array
                    items:
                      type: object
                      properties:
                        x:
                          type: integer
                        'y':
                          type: integer
                  stars:
                    type: array
                    items:
                      type: object
                      properties:
                        x:
                          type: integer
                        'y':
                          type: integer
              examples:
                example-1: {}
      operationId: replays
      description: Replays the current state of the simulation - rewind 1 - forward 1

components:
  schemas: {}
